### ISSUE TITLE
Mineflayer cannot load this plugin if it is installed with pnpm

### ISSUE THREAD

**Issue by unclamped** [link-discord/mineflayer-auto-eat#28]
After doing some testing locally in my fork of [2bored2wait](https://github.com/Enchoseon/2based2wait/), and after trying to [migrate from npm to pnpm](https://github.com/unclamped/2based2wait/commit/b8d487ab3482343fb6be7ff045939f2c6ca07c53), I found that this plugin would no longer be loaded by Mineflayer, and instead cause a crash.
The crash originates on line 16 of Mineflayer's plugin loader, where it checks if the argument it has been passed (what should be the const of the required plugin) is a function or not:
![image](https://user-images.githubusercontent.com/104658278/217425002-0ea791c0-bc9b-408f-b5a2-2bd3d7958992.png)
If not, it fails. 
In the code, the plugin is imported with `const autoeat = require("mineflayer-auto-eat").default;`. Then, it tries to load that plugin and others, which is when it then calls the loadPlugin function that I talked about previously.
![image](https://user-images.githubusercontent.com/104658278/217425799-5ec34c56-1bd4-486a-9a22-bd100a71e7de.png)
(in the screenshot it also shows a different plugin being loaded. I confirmed that it was auto-eat the one generating the issue, as shown in the following screenshot)
![image](https://user-images.githubusercontent.com/104658278/217426158-6a0f9579-701a-45d7-a10a-31e82d7e0fd2.png)
I tried looking at this plugin's code to see what the issue could be, but A- I am way too tired for today, and B- I didn't find anything obvious.

**Comment by unclamped** [comment]
turns out it was because there was a `.default` added in the end, when it should've been `.plugin`. I have no ideas as to why that happened, apologies

**Comment by unclamped** [comment]
wait actually, no, why would npm work with it but not pnpm

**Comment by link-discord** [comment]
Gonna check this sometime

**Comment by link-discord** [comment]
In my testing I was able to install & use mineflayer-auto-eat just fine with pnpm. Are you sure its not an error in the code you wrote?

**Comment by link-discord** [comment]
Will close this issue otherwise

**Comment by belohnung** [comment]
i get the same issue
